---
swagger: "2.0"
info:
  description: "permissions REST services"
  version: "24.0.5"
  title: "ARLAS permissions API"
  contact:
    name: "Gisaia"
    url: "http://www.gisaia.com/"
    email: "contact@gisaia.com"
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/arlas_permissions_server"
tags:
- name: "authorize"
schemes:
- "http"
- "https"
paths:
  /authorize/resources:
    get:
      tags:
      - "authorize"
      summary: "Returns a list of permissions for the current context/user"
      description: "Returns a list of permissions for the current context/user"
      operationId: "get"
      consumes:
      - "application/json;charset=utf-8"
      produces:
      - "application/json;charset=utf-8"
      parameters:
      - name: "filter"
        in: "query"
        description: "A regex to apply to permissions uris in order to filter the\
          \ returned list."
        required: true
        type: "string"
      - name: "pretty"
        in: "query"
        description: "Pretty print"
        required: false
        type: "boolean"
        default: false
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Resource"
        "500":
          description: "Arlas Permissions Error."
          schema:
            $ref: "#/definitions/Error"
definitions:
  Resource:
    type: "object"
    required:
    - "path"
    - "verb"
    properties:
      verb:
        type: "string"
      path:
        type: "string"
  Error:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      error:
        type: "string"
