version: '3'

services:
  arlas-permissions-server:
    build:
      context: ../..
      dockerfile: ${DOCKERFILE:-docker/docker-files/Dockerfile-package-only}
    image: gisaia/arlas-permissions-server:${ARLAS_PERMISSIONS_SERVER_VERSION:-latest}
    container_name: arlas-permissions-server
    environment:
      - ARLAS_PERMISSIONS_PORT="${ARLAS_PERMISSIONS_PORT:-9997}"
      - ARLAS_PERMISSIONS_PREFIX="${ARLAS_PERMISSIONS_PREFIX:-/arlas_permissions_server}"
      - ARLAS_PERMISSIONS_APP_PATH="${ARLAS_PERMISSIONS_APP_PATH:-/}"
      - ARLAS_CORS_ENABLED="${ARLAS_CORS_ENABLED:-false}"
      - ARLAS_AUTH_POLICY_CLASS="${ARLAS_AUTH_POLICY_CLASS:-io.arlas.filter.impl.NoPolicyEnforcer}"
      - ARLAS_AUTH_PERMISSION_URL="${ARLAS_AUTH_PERMISSION_URL:-http://arlas-iam-server:9990/arlas_iam_server/permissions}"
      - ARLAS_AUTH_CERT_URL="${ARLAS_AUTH_CERT_URL}"
      - ARLAS_PERMISSIONS_CACHE_FACTORY_CLASS="${ARLAS_PERMISSIONS_CACHE_FACTORY_CLASS:-io.arlas.commons.cache.BaseHazelcastCacheFactory}"
      - ARLAS_CACHE_TIMEOUT="${ARLAS_CACHE_TIMEOUT:-5}"
    ports:
      - 19997:9997
    healthcheck:
      test: ["CMD","java","HttpHealthcheck.java","http://localhost:9997/admin/healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 3
