###################
# PACKAGING STAGE #
###################
FROM gisaia/arlas-openjdk-17-distroless:20250402102614

# application placed into /opt/app
WORKDIR /opt/app
ADD arlas-permissions-server/target/arlas-permissions-server*.jar /opt/app/arlas-permissions-server.jar
ADD conf/configuration.yaml /opt/app/configuration.yaml
EXPOSE 9997

ENV JDK_JAVA_OPTIONS="-Xmx512m -XX:+ExitOnOutOfMemoryError"
CMD ["arlas-permissions-server.jar", "server", "/opt/app/configuration.yaml"]
