version: '3'

services:
  arlas-permissions-server:
    build:
      context: ../..
      dockerfile: ${DOCKERFILE:-docker/docker-files/Dockerfile-package-only}
    image: gisaia/arlas-permissions-server:${ARLAS_VERSION:-latest}
    container_name: arlas-permissions-server
    environment:
      - ARLAS_PERMISSIONS_PORT="${ARLAS_PERMISSIONS_PORT:-9997}"
      - ARLAS_PERMISSIONS_PREFIX="${ARLAS_PERMISSIONS_PREFIX:-/arlas_permissions_server}"
      - ARLAS_PERMISSIONS_APP_PATH="${ARLAS_PERMISSIONS_APP_PATH:-/}"
      - ARLAS_CORS_ENABLED="${ARLAS_CORS_ENABLED:-false}"
      - ARLAS_AUTH_ENABLED="${ARLAS_AUTH_ENABLED:-true}"
      - ARLAS_AUTH_CERT_URL="${ARLAS_AUTH_CERT_URL}"
    ports:
      - 19997:9997
    command: ["/opt/app/start.sh"]
